### ISSUE TITLE
Arrows

### ISSUE THREAD

**Issue by MattinNajafi** [Spencer6497/free-shuffle#1]
Is there any way of generating arrows in the direction of the route?

**Comment by Spencer6497** [comment]
The route arrows are currently being generated, though they’re a bit hard to see.
![IMG_2246](https://github.com/user-attachments/assets/d142763f-c6c1-4a07-afdc-f3b4bad9030f)

**Comment by MattinNajafi** [comment]
Great! Thank you for this.
